image: docker:19.03.14
services:
- docker:dind

include: .gitlab-pipeline/stages.yml

stages:
  - build
  - test

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

## Stages to build images
build_bi_rtx:
  stage: build
  extends:
    .build_image

build_dst_rtx:
  stage: build
  extends:
    .build_image

build_net_bi_rtx:
  stage: build
  extends:
    .build_image

build_net_dst_rtx:
  stage: build
  extends:
    .build_image

build_net_src_rtx:
  stage: build
  extends:
    .build_image

build_src_rtx:
  stage: build
  extends:
    .build_image

## Stages to test images
test_bi_rtx:
  stage: test
  extends:
    .test_image

test_dst_rtx:
  stage: test
  extends:
    .test_image

test_net_bi_rtx:
  stage: test
  extends:
    .test_image

test_net_dst_rtx:
  stage: test
  extends:
    .test_image

test_net_src_rtx:
  stage: test
  extends:
    .test_image

test_src_rtx:
  stage: test
  extends:
    .test_image
